
"""
For a given state generate summaries for its senators & and representatives in the districts.
Uses a 2 phased approach where Phase 1: Perplexity Sonar Pro API does web searches to scrape internet for all relevant information (2-5 calls max)
    stores that information in data-raw/web-search/[stateCode]/raw-information.txt
Phase 2: Sonnet API reads the information generated by perplexity and summaries it according to the instructions. 
    Output should be markdown files in
        for senators: /public/content/senator-info
        for reps: /public/content/rep-info
NOTE: need to figure out how to create env? venv? with private API keys (to be gitignored)
"""
        
''''
========================================================================================================================
Phase 1 Request Perplexity API for Raw Data
========================================================================================================================
'''
# TODO rate limits & error handling: ~1 second delay between calls; try/excapt for each API call; rety with backoff (if rate limited or server error wait 5 seconds and try up to 3 times)
'''
========================================================================================================================
Request Claude Sonnet for Summary
========================================================================================================================
'''
# TODO check if the file already exists/"resume" mechanism - if it already exists easily restart the script without re-processing

# instructions:
#   write a summary for this legislator. Word count is 250 maximum. Use **bold** for key terms or improtant points. Use this exact structure:
#   ---
#   name: [Full Name]
#   state: [stateCode]
#   district: [districtCode] // only if applicable
#   party: [Party]
#   ---
#   Introduce the legislator ("Sen. (or Rep.) lastName represents (state & district (if applicable))"). Explain their ideology, hometown, socioeconomic background, and stated beliefs.
#   Explain their campaign platform including what they campaigned on and key policy promises
#   Explain anything notable about them: accomplishments, controversies, distinguishing facts

# TODO return a markdown file. Either located in "public/content/senator-info/[stateCode]-firstName-lastName" for senators
# or in "public/content/rep-info/[stateCode]-[district]-firstName-lastName" for representatives
# TODO add the summary to the politican object
